# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stripe_user_id',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
