# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
